use serde::{Deserialize, Deserializer, Serialize, Serializer};

#[repr(u8)]
#[derive(Debug, Copy, Clone)]
pub enum DestinyActivityModeType {
    None = 0,
    Story = 2,
    Strike = 3,
    Raid = 4,
    AllPvP = 5,
    Patrol = 6,
    AllPvE = 7,
    Reserved9 = 9,
    Control = 10,
    Reserved11 = 11,
    Clash = 12,
    Reserved13 = 13,
    CrimsonDoubles = 15,
    Nightfall = 16,
    HeroicNightfall = 17,
    AllStrikes = 18,
    IronBanner = 19,
    Reserved20 = 20,
    Reserved21 = 21,
    Reserved22 = 22,
    Reserved24 = 24,
    AllMayhem = 25,
    Reserved26 = 26,
    Reserved27 = 27,
    Reserved28 = 28,
    Reserved29 = 29,
    Reserved30 = 30,
    Supremacy = 31,
    PrivateMatchesAll = 32,
    Survival = 37,
    Countdown = 38,
    TrialsOfTheNine = 39,
    Social = 40,
    TrialsCountdown = 41,
    TrialsSurvival = 42,
    IronBannerControl = 43,
    IronBannerClash = 44,
    IronBannerSupremacy = 45,
    ScoredNightfall = 46,
    ScoredHeroicNightfall = 47,
    Rumble = 48,
    AllDoubles = 49,
    Doubles = 50,
    PrivateMatchesClash = 51,
    PrivateMatchesControl = 52,
    PrivateMatchesSupremacy = 53,
    PrivateMatchesCountdown = 54,
    PrivateMatchesSurvival = 55,
    PrivateMatchesMayhem = 56,
    PrivateMatchesRumble = 57,
    HeroicAdventure = 58,
    Showdown = 59,
    Lockdown = 60,
    Scorched = 61,
    ScorchedTeam = 62,
    Gambit = 63,
    AllPvECompetitive = 64,
    Breakthrough = 65,
    BlackArmoryRun = 66,
    Salvage = 67,
    IronBannerSalvage = 68,
    PvPCompetitive = 69,
    PvPQuickplay = 70,
    ClashQuickplay = 71,
    ClashCompetitive = 72,
    ControlQuickplay = 73,
    ControlCompetitive = 74,
    GambitPrime = 75,
    Reckoning = 76,
    Menagerie = 77,
    VexOffensive = 78,
    NightmareHunt = 79,
    Elimination = 80,
    Momentum = 81,
    Dungeon = 82,
    Sundial = 83,
    TrialsOfOsiris = 84,
    Dares = 85,
    Offensive = 86,
    LostSector = 87,
    Rift = 88,
    ZoneControl = 89,
    IronBannerRift = 90,
    IronBannerZoneControl = 91,
}

impl<'de> Deserialize<'de> for DestinyActivityModeType {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = u16::deserialize(deserializer)?;
        match s {
            0 => Ok(Self::None),
            2 => Ok(Self::Story),
            3 => Ok(Self::Strike),
            4 => Ok(Self::Raid),
            5 => Ok(Self::AllPvP),
            6 => Ok(Self::Patrol),
            7 => Ok(Self::AllPvE),
            9 => Ok(Self::Reserved9),
            10 => Ok(Self::Control),
            11 => Ok(Self::Reserved11),
            12 => Ok(Self::Clash),
            13 => Ok(Self::Reserved13),
            15 => Ok(Self::CrimsonDoubles),
            16 => Ok(Self::Nightfall),
            17 => Ok(Self::HeroicNightfall),
            18 => Ok(Self::AllStrikes),
            19 => Ok(Self::IronBanner),
            20 => Ok(Self::Reserved20),
            21 => Ok(Self::Reserved21),
            22 => Ok(Self::Reserved22),
            24 => Ok(Self::Reserved24),
            25 => Ok(Self::AllMayhem),
            26 => Ok(Self::Reserved26),
            27 => Ok(Self::Reserved27),
            28 => Ok(Self::Reserved28),
            29 => Ok(Self::Reserved29),
            30 => Ok(Self::Reserved30),
            31 => Ok(Self::Supremacy),
            32 => Ok(Self::PrivateMatchesAll),
            37 => Ok(Self::Survival),
            38 => Ok(Self::Countdown),
            39 => Ok(Self::TrialsOfTheNine),
            40 => Ok(Self::Social),
            41 => Ok(Self::TrialsCountdown),
            42 => Ok(Self::TrialsSurvival),
            43 => Ok(Self::IronBannerControl),
            44 => Ok(Self::IronBannerClash),
            45 => Ok(Self::IronBannerSupremacy),
            46 => Ok(Self::ScoredNightfall),
            47 => Ok(Self::ScoredHeroicNightfall),
            48 => Ok(Self::Rumble),
            49 => Ok(Self::AllDoubles),
            50 => Ok(Self::Doubles),
            51 => Ok(Self::PrivateMatchesClash),
            52 => Ok(Self::PrivateMatchesControl),
            53 => Ok(Self::PrivateMatchesSupremacy),
            54 => Ok(Self::PrivateMatchesCountdown),
            55 => Ok(Self::PrivateMatchesSurvival),
            56 => Ok(Self::PrivateMatchesMayhem),
            57 => Ok(Self::PrivateMatchesRumble),
            58 => Ok(Self::HeroicAdventure),
            59 => Ok(Self::Showdown),
            60 => Ok(Self::Lockdown),
            61 => Ok(Self::Scorched),
            62 => Ok(Self::ScorchedTeam),
            63 => Ok(Self::Gambit),
            64 => Ok(Self::AllPvECompetitive),
            65 => Ok(Self::Breakthrough),
            66 => Ok(Self::BlackArmoryRun),
            67 => Ok(Self::Salvage),
            68 => Ok(Self::IronBannerSalvage),
            69 => Ok(Self::PvPCompetitive),
            70 => Ok(Self::PvPQuickplay),
            71 => Ok(Self::ClashQuickplay),
            72 => Ok(Self::ClashCompetitive),
            73 => Ok(Self::ControlQuickplay),
            74 => Ok(Self::ControlCompetitive),
            75 => Ok(Self::GambitPrime),
            76 => Ok(Self::Reckoning),
            77 => Ok(Self::Menagerie),
            78 => Ok(Self::VexOffensive),
            79 => Ok(Self::NightmareHunt),
            80 => Ok(Self::Elimination),
            81 => Ok(Self::Momentum),
            82 => Ok(Self::Dungeon),
            83 => Ok(Self::Sundial),
            84 => Ok(Self::TrialsOfOsiris),
            85 => Ok(Self::Dares),
            86 => Ok(Self::Offensive),
            87 => Ok(Self::LostSector),
            88 => Ok(Self::Rift),
            89 => Ok(Self::ZoneControl),
            90 => Ok(Self::IronBannerRift),
            91 => Ok(Self::IronBannerZoneControl),
            _ => Err(serde::de::Error::custom(format!(
                "unknown DestinyActivityModeType: {s}",
            ))),
        }
    }
}

impl Serialize for DestinyActivityModeType {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let s = *self as u8;
        s.serialize(serializer)
    }
}
